import Footer from "../components/template-navbar/Footer.jsx";
import Navbar from "../components/template-navbar/Navbar.jsx";
import "../globals.css";

export const metadata = {
  title: "Memorability",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
